### ISSUE TITLE
关于和ADJSCC的对比

### ISSUE THREAD

**Issue by fake-learn** [KeYang8/WITT#22]
![image](https://github.com/KeYang8/WITT/assets/133783979/e6e73730-ff54-4dec-a36a-72567b384971)
作者你好，论文文中并没有和ADJSCC这个模型的性能进行对比，为什么此处要和ADJSCC进行参数的对比呢？

**Comment by wsxtyrdd** [comment]
Thank you for your question. The performance of the ADJSCC model is nearly identical to the Deep JSCC model discussed in our paper. We chose to compare them because WITT employs Channel ModNet for SNR adaption, which is a feature first introduced in ADJSCC. This comparison aims to highlight the efficiency of SNR adaptivity in modern contexts.

I apologize for any confusion caused by the omission in the paper. We appreciate your attention to detail.
